// Muse Pocket Office. SPDX-License-Identifier: Apache-2.0
#pragma once
#include "raster.h"

namespace pocket_office {
// Selected by font() in raster.cpp; generated by tools/office/build_fonts.py.
extern const Font fonts[];
}
